### ISSUE TITLE
Crash with Optifine

### ISSUE THREAD

**Issue by 2mal3** [Patbox/EntityViewDistance#1]
If you click on Options after starting Minecraft, the game crashes. 
Everything else should be in the crash log.

[crash-2022-01-18_16.29.46-client.txt](https://github.com/Patbox/EntityViewDistance/files/7890287/crash-2022-01-18_16.29.46-client.txt)

**Comment by Patbox** [comment]
https://lambdaurora.dev/optifine_alternatives/

**Comment by supsm** [comment]
L
