### ISSUE TITLE
Game crashes when clicked on "entity distance settings"

### ISSUE THREAD

**Issue by Taiyou06** [Patbox/EntityViewDistance#7]
Game version: 1.20.4
Mod version: 1.2.0
Log: https://mclo.gs/0lOZ9QF

**Comment by Patbox** [comment]
Your unofficial verdion of lambdynamicgrass loads outdated version of spruceui, causing a crash.

**Comment by Taiyou06** [comment]
> Your unofficial verdion of lambdynamicgrass loads outdated version of spruceui, causing a crash.

I don't have that mod in the first place. I only have LambDynamicLight even when i disable that the crash is still presistent; https://mclo.gs/OhYeRBv

**Comment by Patbox** [comment]
Now it's enhancedblockentities bundling outdated one

**Comment by Taiyou06** [comment]
> Now it's enhancedblockentities bundling outdated one

Ah i see, that solved the issue yeah. I'll contact the other devs about it, ty for helping out!
